package com.david.biblia.ui
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import kotlinx.coroutines.launch

@Composable private fun Header(title:String,sub:String?=null){Column(Modifier.padding(20.dp)){Text(title,style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.SemiBold);sub?.let{Text(it,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}
@Composable fun HomeScreen(vm:AppViewModel,open:(String,Int)->Unit){val p by vm.prefs.collectAsState();LazyColumn(Modifier.fillMaxSize()){item{Header("Biblia","Lectura, estudio y planes")};item{Card(Modifier.padding(16.dp).fillMaxWidth()){Column(Modifier.padding(20.dp)){Text("Continuar leyendo",style=MaterialTheme.typography.titleMedium);Text("${vm.repo.books.find{it.id==p.book}?.name?:p.book} ${p.chapter}",style=MaterialTheme.typography.headlineSmall);Button({open(p.book,p.chapter)}){Text("Continuar")}}}};item{Card(Modifier.padding(horizontal=16.dp).fillMaxWidth()){Column(Modifier.padding(20.dp)){Text("Plan anual",fontWeight=FontWeight.Bold);Text("Avanza cada día y conserva tu progreso local.");TextButton({}){Text("Disponible en Planes")}}}};item{TextButton({},Modifier.padding(16.dp)){Text("Todo funciona sin conexión una vez instalado el corpus bíblico.")}}}}

@Composable fun LibraryScreen(vm:AppViewModel,open:(String,Int)->Unit){var testament by remember{mutableStateOf("OT")};Column{Header("Biblioteca");SingleChoiceSegmentedButtonRow(Modifier.padding(horizontal=16.dp)){listOf("OT" to "Antiguo","NT" to "Nuevo").forEachIndexed{i,p->SegmentedButton(testament==p.first,{testament=p.first},SegmentedButtonDefaults.itemShape(i,2)){Text(p.second)}}};LazyColumn{items(vm.repo.books.filter{it.testament==testament}){b->ListItem(headlineContent={Text(b.name)},supportingContent={Text("${b.chapters} capítulos")},trailingContent={Icon(Icons.Default.ChevronRight,null)},modifier=Modifier.clickable{open(b.id,1)})}}}}

@Composable fun SearchScreen(vm:AppViewModel,initial:String,open:(String,Int)->Unit){val p by vm.prefs.collectAsState();var q by remember{mutableStateOf(initial)};var result by remember{mutableStateOf(emptyList<com.david.biblia.data.Verse>())};Column{Header("Buscar");Row(Modifier.padding(16.dp)){OutlinedTextField(q,{q=it},Modifier.weight(1f),placeholder={Text("Palabra o frase")});IconButton({result=vm.repo.search(p.version,q)}){Icon(Icons.Default.Search,null)}};if(!vm.repo.available(p.version)) Text("El corpus ${p.version} aún no está instalado. Ejecuta tools/import_usfm.py.",Modifier.padding(16.dp));LazyColumn{items(result){v->ListItem(headlineContent={Text("${vm.repo.books.find{it.id==v.bookId}?.name} ${v.chapter}:${v.verse}")},supportingContent={Text(v.text,maxLines=3)},modifier=Modifier.clickable{open(v.bookId,v.chapter)})}}}}

@Composable fun PlansScreen(vm:AppViewModel,openRef:(String)->Unit){var selected by remember{mutableStateOf(vm.repo.plans.firstOrNull()?.id?:"")};val scope=rememberCoroutineScope();val progress= if(selected.isNotBlank()) vm.dao.progress(selected).collectAsState(initial=emptyList()).value else emptyList();Column{Header("Planes de lectura");LazyRow(contentPadding=PaddingValues(16.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){items(vm.repo.plans){p->FilterChip(selected==p.id,{selected=p.id},label={Text(p.name)})}};LazyColumn{items(vm.repo.planEntries.filter{it.planId==selected}){e->val done=progress.any{it.day==e.day&&it.completed};Card(Modifier.padding(horizontal=16.dp,vertical=5.dp).fillMaxWidth()){Column(Modifier.padding(16.dp)){Row(verticalAlignment=Alignment.CenterVertically){Checkbox(done,{vm.setProgress(selected,e.day,it)});Text("Día ${e.day}",fontWeight=FontWeight.Bold)};e.passages.forEach{TextButton({openRef(it)}){Text(it)}}}}}}}}

@Composable fun TopicsScreen(vm:AppViewModel,openRef:(String)->Unit){Column{Header("Para cada necesidad");LazyColumn{items(vm.repo.topics){t->var ex by remember{mutableStateOf(false)};Card(Modifier.padding(horizontal=16.dp,vertical=5.dp).fillMaxWidth()){Column{ListItem(headlineContent={Text(t.name)},trailingContent={Icon(if(ex)Icons.Default.ExpandLess else Icons.Default.ExpandMore,null)},modifier=Modifier.clickable{ex=!ex});if(ex)t.references.forEach{TextButton({openRef(it)},Modifier.padding(start=12.dp)){Text(it)}}}}}}}}

@Composable fun FavoritesScreen(vm:AppViewModel,open:(String,Int)->Unit){val fav by vm.favorites.collectAsState();Column{Header("Favoritos");LazyColumn{items(fav){f->ListItem(headlineContent={Text("${vm.repo.books.find{it.id==f.bookId}?.name} ${f.chapter}:${f.verse}")},modifier=Modifier.clickable{open(f.bookId,f.chapter)})}}}}

@Composable fun BookInfoScreen(vm:AppViewModel,book:String,open:(String)->Unit){val b=vm.repo.books.find{it.id==book};val i=vm.repo.bookInfo.find{it.bookId==book};LazyColumn(Modifier.padding(20.dp)){item{Text(b?.name?:book,style=MaterialTheme.typography.headlineLarge,fontWeight=FontWeight.Bold)};i?.let{item{InfoBlock("Autor",it.author);InfoBlock("Fecha",it.date);InfoBlock("Contexto",it.context);InfoBlock("Propósito",it.purpose);InfoBlock("Temas",it.themes.joinToString(" • "));InfoBlock("Estructura",it.outline.joinToString("
"));Button({open(book)}){Text("Comenzar lectura")}}}}}
@Composable private fun InfoBlock(t:String,v:String){Spacer(Modifier.height(18.dp));Text(t,fontWeight=FontWeight.Bold);Text(v)}

@Composable fun SettingsScreen(vm:AppViewModel){val p by vm.prefs.collectAsState();Column(Modifier.verticalScroll(rememberScrollState())){Header("Ajustes");Text("Versión",Modifier.padding(horizontal=16.dp),fontWeight=FontWeight.Bold);vm.repo.versions.forEach{v->ListItem(headlineContent={Text(v.name)},supportingContent={Text(if(vm.repo.available(v.id))v.license else "Corpus no instalado • ${v.license}")},leadingContent={RadioButton(p.version==v.id,{vm.updatePrefs{it.copy(version=v.id)}})})};HorizontalDivider();Text("Tamaño de texto: ${p.fontSize}",Modifier.padding(16.dp));Slider(p.fontSize.toFloat(),{n->vm.updatePrefs{it.copy(fontSize=n.toInt())}},valueRange=14f..30f,modifier=Modifier.padding(horizontal=16.dp));Text("Tema",Modifier.padding(16.dp),fontWeight=FontWeight.Bold);Row(Modifier.padding(horizontal=16.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){listOf("light" to "Claro","sepia" to "Sepia","dark" to "Oscuro").forEach{(id,n)->FilterChip(p.theme==id,{vm.updatePrefs{it.copy(theme=id)}},label={Text(n)})}};ListItem(headlineContent={Text("Cambio de hoja")},supportingContent={Text("Animación horizontal tipo libro")},trailingContent={Switch(p.pageMode,{vm.updatePrefs{p->p.copy(pageMode=it)}})})}}
